version: '3.5'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: bundle exec rails s -b '0.0.0.0' -p 5000
    volumes:
      - .:/usr/src/tickets_app
    env_file:
      - .env
    tty: true
    stdin_open: true
